=begin
#ORY Hydra

#Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.

OpenAPI spec version: latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for HydraClient::EmptyResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmptyResponse' do
  before do
    # run before each test
    @instance = HydraClient::EmptyResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmptyResponse' do
    it 'should create an instance of EmptyResponse' do
      expect(@instance).to be_instance_of(HydraClient::EmptyResponse)
    end
  end
end
