=begin
#ORY Hydra

#Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.

OpenAPI spec version: latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'hydra_client/api_client'
require 'hydra_client/api_error'
require 'hydra_client/version'
require 'hydra_client/configuration'

# Models
require 'hydra_client/models/accept_consent_request'
require 'hydra_client/models/accept_login_request'
require 'hydra_client/models/completed_request'
require 'hydra_client/models/consent_request'
require 'hydra_client/models/consent_request_session'
require 'hydra_client/models/empty_response'
require 'hydra_client/models/flush_inactive_o_auth2_tokens_request'
require 'hydra_client/models/generic_error'
require 'hydra_client/models/health_not_ready_status'
require 'hydra_client/models/health_status'
require 'hydra_client/models/json_web_key'
require 'hydra_client/models/json_web_key_set'
require 'hydra_client/models/json_web_key_set_generator_request'
require 'hydra_client/models/login_request'
require 'hydra_client/models/logout_request'
require 'hydra_client/models/o_auth2_client'
require 'hydra_client/models/o_auth2_token_introspection'
require 'hydra_client/models/oauth2_token_response'
require 'hydra_client/models/oauth_token_response'
require 'hydra_client/models/open_id_connect_context'
require 'hydra_client/models/previous_consent_session'
require 'hydra_client/models/reject_request'
require 'hydra_client/models/swagger_flush_inactive_access_tokens'
require 'hydra_client/models/swagger_json_web_key_query'
require 'hydra_client/models/swagger_jwk_create_set'
require 'hydra_client/models/swagger_jwk_set_query'
require 'hydra_client/models/swagger_jwk_update_set'
require 'hydra_client/models/swagger_jwk_update_set_key'
require 'hydra_client/models/swagger_o_auth_introspection_request'
require 'hydra_client/models/swagger_revoke_o_auth2_token_parameters'
require 'hydra_client/models/swaggeroauth2_token_parameters'
require 'hydra_client/models/userinfo_response'
require 'hydra_client/models/version'
require 'hydra_client/models/well_known'

# APIs
require 'hydra_client/api/admin_api'
require 'hydra_client/api/health_api'
require 'hydra_client/api/public_api'
require 'hydra_client/api/version_api'

module HydraClient
  class << self
    # Customize default settings for the SDK using block.
    #   HydraClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
